project:
  type: website
  output-dir: docs
  resources: 
    -  "files/"

website:
  title: "Sebastian Hanika"
  navbar:
    left:
      - href: research.qmd
        text: research
      - href: teaching.qmd
        text: teaching

format:
  html:
    theme: [litera, styles.scss]
    toc: false




